### ISSUE TITLE
UI blocks when receiving HTTP 406 response

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/driver-spec-runner#15]
**Describe the bug**
When a request to `/test` returns a HTTP 406 response, the output in the runner UI blocks indefinitely with a loading spinner.

**Expected behavior**
Failure should be noted and made visible.

**Screenshots**
![EDE7D692-10E5-4230-AB80-0C36D2434174](https://user-images.githubusercontent.com/843652/135942800-bf04f9b7-1c55-4416-b724-ed7a3e694498.jpeg)

**Additional context**
Similar behaviour may be evident for other non 200/500 response codes.

**Comment by MrYuion** [comment]
Hmm... The frontend does look to be handling errors correctly. 
I've made a tweak which might fix a potential issue. 
Can you let me know if there are any console errors when this occurs?
@kimburgess @caspiano
